### ISSUE TITLE
feature request: documentation improvements

### ISSUE THREAD

**Issue by curt-f** [brain-research/deep-molecular-massspec#13]
I got the pre-trained model to predict spectra!

This package seems to require `absl-py` installable with `pip`, as well as specific versions of tensorflow such as `tensorflow=1.13.2`, and `matplotlib`.

Very minor suggested tweak to README.md:

> Most of the packages required here can be installed with `conda install tensorflow=1.13.2 rdkit matplotlib` and `pip install abls-py`.

**Comment by jnwei** [comment]
Thanks for the suggestion! Do you mind sending a PR and I can approve it?

**Comment by jnwei** [comment]
Updated the docs accordingly. Thanks for the suggestion!
