### ISSUE TITLE
install tensorflow

### ISSUE THREAD

**Issue by porunga00** [brain-research/deep-molecular-massspec#15]
In README
"Most of the packages required here can be installed with conda install tensorflow=1.13.2 rdkit matplotlib and pip install abls-py."

but, conda does'nt have tensorflow=1.13.2.
Can ```conda install tensorflow=1.13.1``` or ```pip install tensorflow=1.13.2``` go?

**Comment by jnwei** [comment]
I believe tensorflow 1.13.1 should also work. Let me know if it doesn't and I'll take a closer look.

**Comment by porunga00** [comment]
It work well! 
Thank you!
