### ISSUE TITLE
How to retrain

### ISSUE THREAD

**Issue by porunga00** [brain-research/deep-molecular-massspec#16]
Can I retrain with my own MS SDF?

**Comment by jnwei** [comment]
Yes it should be possible

**Comment by jnwei** [comment]
Let me know if you run into any issues; feel free to reopen this comment if so.

**Comment by dchek001** [comment]
I have a somewhat related and perhaps rather naive question. My apologies - I am new to DNN. Retraining with your own MS data would not change the underlying NEIMS architecture and only re-optimize the weights, probably only in the output layer? Is that right? Thanks!

**Comment by jnwei** [comment]
Right. You are also welcome to change the hyperparameters of the model by specifying hyperparameters with the hparams flag. For example, to change the number of hidden units in the DNN to 1500, you can use:

python molecule_estimator.py --hparams=num_hidden_units=1500

**Comment by dchek001** [comment]
Thanks! Much appreciated.
