### ISSUE TITLE
first line in predicted spectrum

### ISSUE THREAD

**Issue by dchek001** [brain-research/deep-molecular-massspec#18]
Hello,

I've noticed that for a very small fraction of MS spectra generated by NEIMS the spectral part starts with the line with m/z=0, like this

>  <PREDICTED SPECTRUM>  (1) 
0 9
18 4
25 2
26 38

Could it be because of some rounding error? I am attaching a small SD file with several molecules from FragranceDB to illustrate this.

If you skip such first lines, or manually delete them from the SD files, the rest of the predicted MS spectra can match quit well the observed MS spectra from the NIST library. 

Thanks!

[Example_031020.sdf.txt](https://github.com/brain-research/deep-molecular-massspec/files/4314442/Example_031020.sdf.txt)

**Comment by jnwei** [comment]
Hi, thanks for the interest.

We don't do anything to explicitly zero out intensities for m/z=0, so I suspect it is some noise. If you can get by removing it, that sounds like the easiest solution.

Happy to hear that it otherwise fits the FragranceDB well.

**Comment by dchek001** [comment]
Thank you very much for the quick reply!

It is certainly not a problem, I find only a very small percentage of the
predicted spectra, less than 0.5%, to carry this.

Many thanks again!
