### ISSUE TITLE
how to get plot figures

### ISSUE THREAD

**Issue by jingxual** [brain-research/deep-molecular-massspec#21]
@jnwei 
Hi!  I have several questions

1.  After I  'Run the model prediction on the example molecule' by typing the following command lines

> $ python make_spectra_prediction.py \
> --input_file=examples/pentachlorobenzene.sdf \
> --output_file=/tmp/annotated.sdf \
> --weights_dir=$MODEL_WEIGHTS_DIR/massspec_weights

how can I get the spectrum figures?

2. If I want to retrain the model with my own data and test that model, what sholud the '--input_file=' be?
I found it did not generate a .gz file in neighter data-splitting process nor model-training process. So, I was confused where was test_14_record.gz file from (or what should I type to generate this file). Also, this .gz file is unreadable. 

> python make_predictions_from_tfrecord.py \
> --input_file=testdata/test_14_record.gz \
> --output_file=tmp/massspec_predictions/models/output_predictions/ \
> --model_checkpoint_path=tmp/massspec_predictions/models/output/ \
> --hparams=eval_batch_size=16 \
> --alsologtostderr

Thanks in advance!!!

**Comment by jnwei** [comment]
Hi @jingxual,

Thanks for you interest in our project!

1. For plotting spectra, you can try using the function plot_spectra_utils.plot_true_and_predicted_spectra after making the spectral predictions. You can either reload the predicted spectra from the sdf files (parse_sdf_utils.get_sdf_to_mol might be useful here), or else add a method to the predictor that calls the spectra plot function before saving the spectra to sdfs.

2. Your input to make_predictions_from_tfrecord.py should be a TFRecord file. Please see the Model_Retrain_Quickstart.md guide for more information. Note that molecule_estimator.py is used to train a new model, and make_predictions_from_tfrecord.py makes predictions from a newly trained model. You could also use make_spectra_prediction.py to make predictions directly from an sdf file once you have the trained weights.

Jennifer

**Comment by jingxual** [comment]
Yeah Understood! Thanks for quick response!!!

And,
> "Your input to make_predictions_from_tfrecord.py should be a TFRecord file."
does that mean what your input flie **test_14_record.gz** (--input_file=testdata/test_14_record.gz) is a zip format of all TFRecord files generated in the data splitting process?

THANKS!
Jingxual

**Comment by jnwei** [comment]
test_14_record.gz is contains the parsed contents of a single sdf file, it does not contain the splits dataset files. Please use make_train_test_split.py to construct the record files for each split.
