### ISSUE TITLE
make_prediction.py

### ISSUE THREAD

**Issue by lionelxia** [brain-research/deep-molecular-massspec#22]
Hi! 
I run make_prediction.py.
errors: tensorflow.python.framework.errors_impl.PermissionDeniedError: Failed to delete a file: C:\Users\111\AppData\Local\Temp\tmp49fl8y6t; Permission denied
I tried to delete this file,but it's useless.

Thanks in advance!

**Comment by jnwei** [comment]
Hi, 

It sounds like you don't have read/write permissions in the specified folder (similar to https://stackoverflow.com/questions/41606854/tensorflow-permission-denied-error-location). 

Perhaps you could try to run make_prediction.py in a different folder?
