### ISSUE TITLE
FutureWarning and HDF5 errors

### ISSUE THREAD

**Issue by just-a-chemist** [brain-research/deep-molecular-massspec#24]
Hi, I am quite new to python and am following the quickstart guide. However, I encounter the following error when trying to run the make_spectra_prediction.py command:
(my-rdkit-env) C:\Users\s\Desktop\NEIMS>python make_spectra_prediction.py
C:\Users\s\anaconda3\envs\my-rdkit-env\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\s\anaconda3\envs\my-rdkit-env\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\s\anaconda3\envs\my-rdkit-env\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\s\anaconda3\envs\my-rdkit-env\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\s\anaconda3\envs\my-rdkit-env\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\s\anaconda3\envs\my-rdkit-env\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\s\anaconda3\envs\my-rdkit-env\lib\site-packages\h5py\__init__.py:40: UserWarning: h5py is running against HDF5 1.10.5 when it was built against 1.10.4, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.10.4, library is 1.10.5
        SUMMARY OF THE HDF5 CONFIGURATION
        =================================

General Information:
-------------------
                   HDF5 Version: 1.10.5
                  Configured on: 2019-03-04
                  Configured by: Visual Studio 14 2015 Win64
                    Host system: Windows-10.0.17763
              Uname information: Windows
                       Byte sex: little-endian
             Installation point: C:/Program Files/HDF5

Compiling Options:
------------------
                     Build Mode:
              Debugging Symbols:
                        Asserts:
                      Profiling:
             Optimization Level:

Linking Options:
----------------
                      Libraries:
  Statically Linked Executables: OFF
                        LDFLAGS: /machine:x64
                     H5_LDFLAGS:
                     AM_LDFLAGS:
                Extra libraries:
                       Archiver:
                         Ranlib:

Languages:
----------
                              C: yes
                     C Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe 19.0.24218.1
                       CPPFLAGS:
                    H5_CPPFLAGS:
                    AM_CPPFLAGS:
                         CFLAGS:  /DWIN32 /D_WINDOWS /W3
                      H5_CFLAGS:
                      AM_CFLAGS:
               Shared C Library: YES
               Static C Library: YES

                        Fortran: OFF
               Fortran Compiler:
                  Fortran Flags:
               H5 Fortran Flags:
               AM Fortran Flags:
         Shared Fortran Library: YES
         Static Fortran Library: YES

                            C++: ON
                   C++ Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe 19.0.24218.1
                      C++ Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
                   H5 C++ Flags:
                   AM C++ Flags:
             Shared C++ Library: YES
             Static C++ Library: YES

                            JAVA: OFF
                   JAVA Compiler:

Features:
---------
                   Parallel HDF5: OFF
Parallel Filtered Dataset Writes:
              Large Parallel I/O:
              High-level library: ON
                    Threadsafety: OFF
             Default API mapping: v110
  With deprecated public symbols: ON
          I/O filters (external):  DEFLATE DECODE ENCODE
                             MPE:
                      Direct VFD:
                         dmalloc:
  Packages w/ extra debug output:
                     API Tracing: OFF
            Using memory checker: OFF
 Memory allocation sanity checks: OFF
          Function Stack Tracing: OFF
       Strict File Format Checks: OFF
    Optimization Instrumentation:
Bye...

Please could you help? Thanks in advance and apologies if I have made a silly mistake.

**Comment by jnwei** [comment]
Hi, it sounds like an issue with the h5py package on your system, possibly similar to this issue? https://github.com/h5py/h5py/issues/853

What are you using to load the dependencies? Maybe try recreating the python environment with Anaconda? https://github.com/brain-research/deep-molecular-massspec#required-packages

 I don't have much experience running this repo on Windows, so I'm not sure what differences in instructions if any are required.

**Comment by just-a-chemist** [comment]
Hi thanks, that tip fixed one problem but now I receive the following message:

(my-rdkit-env) C:\Users\s\Desktop\NEIMS>python make_spectra_prediction.py
C:\Users\s\anaconda3\envs\my-rdkit-env\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\s\anaconda3\envs\my-rdkit-env\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\s\anaconda3\envs\my-rdkit-env\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\s\anaconda3\envs\my-rdkit-env\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\s\anaconda3\envs\my-rdkit-env\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\s\anaconda3\envs\my-rdkit-env\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])


What version of numpy should I be using? Thanks.

**Comment by jnwei** [comment]
I was using numpy version 1.15.4.

I think you can safely ignore these warning messages. I believe you should still be able to get the predictions? I think a couple updates to the code itself need to be made to remove the FutureWarning; it isn't a issue on your end.

**Comment by just-a-chemist** [comment]
Hi, I solved the future warning issue (it was bugging me) by installing that verison of numpy. Now the terminal will run the script without generating an error message but still does not return anything. The same thing happens if I try and run the entire command as one line. Should I just try and run on a linux machine? Cheers.

**Comment by jnwei** [comment]
Double checking a few things:

- When you run the command python make_spectra_prediction.py, are you also including the flag arguments? i.e. The full command is: ```python make_spectra_prediction.py --input_file=examples/pentachlorobenzene.sdf --output_file=<desired output location> --weights_dir=<path where you stored the weights>```

If you skip these commands there will not be any output. Instead you'll see an error message like: ```ValueError: Can't load save_path when it is None.```

- Assuming you are following the Quickstart Guide (https://storage.googleapis.com/deep-molecular-massspec/massspec_weights/massspec_weights.zip), are you also downloading and unzipping the weights first?

**Comment by just-a-chemist** [comment]
Hi, yes I have tried the full line too (with and without \) as well as trying to enter line by line. I do not receive that issue on windows 10, only the terminal returing nothing. 

When I install and run this program on the linux cluster at my university I am able to get the annotated.sdf out file. I cannot quite work out the correct command to get the program to plot the spectrum but just parse the bottom part of a file and then plot. Is there any problem in doing this?

I just want to reiterate my graditude for your help and for creating an excellent program! 

All the best.

**Comment by jnwei** [comment]
Hm OK, sorry to hear it's not working on windows.

Yeah parsing out the spectra prediction into your plotting tool of choice is a good way to go here. If you happen to want to use matplotlib to plot these, you can take a look at the function plot_true_and_predicted_spectra in plot_spectra_utils.py 

I'm glad that you have found this useful. Thanks for your interest in our project!
