### ISSUE TITLE
quickstart issues

### ISSUE THREAD

**Issue by chrispook** [brain-research/deep-molecular-massspec#8]
Hello, I've downloaded and unzipped the library. Then I open a bash terminal in that folder and copy the first couple of lines from the quickstart example and hit enter:

TARGET_PATH_NAME=/tmp/massspec_predictions

python make_train_test_split.py \
> --main_sdf_name=testdata/test_14_mend.sdf \
> --replicates_sdf_name=testdata/test_2_mend.sdf \
> --output_master_dir=$TARGET_PATH_NAME/spectra_tf_records \
> --alsologtostderr

This returns the following error:
Traceback (most recent call last):
  File "make_train_test_split.py", line 451, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "make_train_test_split.py", line 400, in main
    tf.gfile.MkDir(FLAGS.output_master_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 409, in create_dir
    create_dir_v2(dirname)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 427, in create_dir_v2
    pywrap_tensorflow.CreateDir(compat.as_bytes(path), status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /tmp/massspec_predictions/spectra_tf_records; No such file or directory

I can't work out why this happens. Could you help me?
Thanks, 
Chris

**Comment by chrispook** [comment]
I created the /massspec_predictions folder in /tmp myself and now I get the following error:

> [09:20:31] Explicit valence for atom # 0 O, 3, is greater than permitted
> [09:20:31] ERROR: Could not sanitize molecule ending on line 917
> [09:20:31] ERROR: Explicit valence for atom # 0 O, 3, is greater than permitted
> W0526 09:20:31.586498 140267811391232 parse_sdf_utils.py:118] Number of failed molblocks : 1
> Traceback (most recent call last):
>   File "make_train_test_split.py", line 451, in <module>
>     app.run(main)
>   File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
>     _run_main(main, args)
>   File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
>     sys.exit(main(argv))
>   File "make_train_test_split.py", line 414, in main
>     FLAGS.main_sdf_name, max_atoms=FLAGS.max_atoms)
>   File "/media/chris/data/Chris_stuff/Google_Drive/KODE/my_Python_code/mass_spec/DeepLearning/deep-molecular-massspec-master/parse_sdf_utils.py", line 142, in get_sdf_to_mol
>     mols = [mol for mol in mols if _mol_passes_filters(mol)]
>   File "/media/chris/data/Chris_stuff/Google_Drive/KODE/my_Python_code/mass_spec/DeepLearning/deep-molecular-massspec-master/parse_sdf_utils.py", line 122, in _mol_passes_filters
>     if not feature_utils.check_mol_has_non_empty_mass_spec_peak_tag(mol):
>   File "/media/chris/data/Chris_stuff/Google_Drive/KODE/my_Python_code/mass_spec/DeepLearning/deep-molecular-massspec-master/feature_utils.py", line 249, in check_mol_has_non_empty_mass_spec_peak_tag
>     return ms_constants.SDF_TAG_MASS_SPEC_PEAKS in mol.GetPropsAsDict().keys()
> AttributeError: 'Mol' object has no attribute 'GetPropsAsDict'

I'm looking into the mol.GetPropsAsDict() function.

**Comment by jnwei** [comment]
We're going to update this repo to Python 3 soon. Hopefully that should resolve this issue.

**Comment by jnwei** [comment]
The repository is now updated to python 3.
